{% set python_ver = "python >=3.7" %}
{% set python_ver = "python >=3.7" %}
{% set name = "cirq" %}
{% set version = "1.1.0" %}
{% set home = "https://quantumai.google/cirq" %}
{% set summary = "An open source framework for programming quantum computers" %}
{% set doc_url = "https://quantumai.google/cirq/install" %}
{% set license = "Apache-2.0" %}
{% set license_file = "LICENSE" %}
{% set python_ver = "python >=3.7" %}


package:
  name: {{ name }}-meta
  version: {{ version }}

source:
  url: https://github.com/quantumlib/Cirq/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 76a9d109fc8b6a084ab813388655ffcb5239552518f82b34705feccaa8f5cb51

build:
  number: 0
  noarch: python

outputs:

  - name: {{ name }}-core
    build:
      noarch: python
    script: build_{{ name }}-core.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - duet-python >=0.2.7,=0.2
        - matplotlib-base >=3.0,=3
        - networkx >=2.4,=2
        - numpy >=1.16,<1.24
        - pandas
        - {{ python_ver }}
        - sortedcontainers >=2.0,=2
        - scipy
        - sympy
        - typing_extensions
        - tqdm

    test:
      imports:
        - {{ name }}
        # Package is named cirq-core but gets imported as cirq
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-core
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-core/{{ license_file }}


  - name: {{ name }}-aqt
    build:
      noarch: python
    script: build_{{ name }}-aqt.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-core =={{ version }}
        - requests >=2.18,=2
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}_aqt
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-aqt
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-aqt/{{ license_file }}


  - name: {{ name }}-web
    build:
      noarch: python
    script: build_{{ name }}-web.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-core =={{ version }}
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}_web
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-web
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-web/{{ license_file }}


  - name: {{ name }}-rigetti
    build:
      noarch: python
    script: build_{{ name }}-rigetti.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-core =={{ version }}
        - pyquil >=3.2.0
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}_rigetti
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-rigetti
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-rigetti/{{ license_file }}


  - name: {{ name }}-pasqal
    build:
      noarch: python
    script: build_{{ name }}-pasqal.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-core =={{ version }}
        - requests >=2.18,=2
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}_pasqal
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-pasqal
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-pasqal/{{ license_file }}


  - name: {{ name }}-ionq
    build:
      noarch: python
    script: build_{{ name }}-ionq.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-core =={{ version }}
        - requests >=2.18,=2
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}_ionq
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-ionq
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-ionq/{{ license_file }}


  - name: {{ name }}-google
    build:
      noarch: python
    script: build_{{ name }}-google.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-core =={{ version }}
        - google-api-core-grpc >=1.14.0,<2.0.0dev
        - protobuf >=3.15.0,<4
        - proto-plus >=1.20.0
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}_google
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq/tree/master/cirq-google
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ name }}-google/{{ license_file }}


  - name: {{ name }}
    build:
      noarch: python
    script: build_{{ name }}.sh

    requirements:
      host:
        - pip
        - {{ python_ver }}
      run:
        - {{ name }}-aqt =={{ version }}
        - {{ name }}-core =={{ version }}
        - {{ name }}-google =={{ version }}
        - {{ name }}-ionq =={{ version }}
        - {{ name }}-pasqal =={{ version }}
        - {{ name }}-rigetti =={{ version }}
        - {{ name }}-web =={{ version }}
        - {{ python_ver }}

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

    about:
      home: {{ home }}
      summary: {{ summary }}
      dev_url: https://github.com/quantumlib/Cirq
      doc_url: {{ doc_url }}
      license: {{ license }}
      license_file: {{ license_file }}


about:
  home: {{ home }}
  summary: {{ summary }}
  description: |
    Cirq is a Python library for writing, manipulating, and optimizing quantum
    circuits and running them against quantum computers and simulators.
  dev_url: https://github.com/quantumlib/Cirq
  doc_url: {{ doc_url }}
  license: {{ license }}
  license_file: {{ license_file }}

extra:
  recipe-maintainers:
    - BastianZim
  feedstock-name: {{ name }}
